#!/usr/bin/env bash
#
# Regenerate nginx's Cloudflare real-IP configuration.
#
# With the Cloudflare proxy enabled, every request reaches the origin from a
# Cloudflare address, so $remote_addr is Cloudflare rather than the visitor.
# Logs become useless for attribution and anything IP-based — rate limiting,
# fail2ban — would act on Cloudflare's ranges instead of the client, which is
# worse than not acting at all.
#
# This writes set_real_ip_from entries for Cloudflare's published ranges and
# tells nginx to take the client address from the CF-Connecting-IP header,
# which Cloudflare sets to the single originating IP. nginx then substitutes
# that into $remote_addr, so both the access log and the X-Real-IP header
# passed through to the application carry the true client address.
#
# Run as root:  sudo ./deploy/cloudflare-realip.sh
#
# Cloudflare changes these ranges rarely, but it does change them. Schedule it
# monthly so the list cannot quietly go stale:
#
#   sudo crontab -e
#   17 4 1 * *  /opt/jmltracker/jmltracker/deploy/cloudflare-realip.sh >/dev/null
#
# Trusting a header is only safe because set_real_ip_from restricts which
# sources may set it. Any request arriving from outside those ranges keeps its
# real source address, so spoofing CF-Connecting-IP directly at the origin
# achieves nothing.

set -euo pipefail

OUT="/etc/nginx/conf.d/cloudflare-realip.conf"
V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must run as root - it writes ${OUT}" >&2
    exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "==> Fetching Cloudflare ranges"
v4="$(curl -fsS --max-time 20 "$V4_URL")"
v6="$(curl -fsS --max-time 20 "$V6_URL")"

# Validate before writing anything. A captive portal or an error page would
# otherwise be written straight into nginx config as garbage, and the only
# symptom would be nginx refusing to start on the next restart.
validate() {
    local label="$1" pattern="$2" list="$3" count=0
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        if [[ ! "$line" =~ $pattern ]]; then
            echo "ERROR: ${label} list contains a non-CIDR line: ${line}" >&2
            exit 1
        fi
        count=$((count + 1))
    done <<< "$list"
    if [[ $count -lt 5 ]]; then
        echo "ERROR: only ${count} ${label} ranges returned - refusing to write" >&2
        exit 1
    fi
    echo "    ${label}: ${count} ranges"
}

validate "IPv4" '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$' "$v4"
validate "IPv6" '^[0-9a-fA-F:]+/[0-9]{1,3}$' "$v6"

{
    echo "# Generated by deploy/cloudflare-realip.sh - do not edit by hand."
    echo "# Regenerated from ${V4_URL} and ${V6_URL}."
    echo
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"
    done <<< "$v4"
    echo
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"
    done <<< "$v6"
    echo
    echo "real_ip_header CF-Connecting-IP;"
    # Only one proxy hop is trusted: Cloudflare talks to this origin directly.
    echo "real_ip_recursive off;"
} > "$tmp"

echo "==> Installing ${OUT}"
backup=""
if [[ -f "$OUT" ]]; then
    backup="${OUT}.bak"
    cp "$OUT" "$backup"
fi
install -m 0644 "$tmp" "$OUT"

echo "==> Testing nginx configuration"
if ! nginx -t; then
    echo "ERROR: nginx rejected the new config - rolling back" >&2
    if [[ -n "$backup" ]]; then
        mv "$backup" "$OUT"
    else
        rm -f "$OUT"
    fi
    nginx -t
    exit 1
fi
rm -f "$backup"

echo "==> Reloading nginx"
systemctl reload nginx
echo "==> Done"
